spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    use_sql_comments: true
    format_sql: true
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/trivago
    username: trivago
    password: trivago123